Repository woowa-techcamp-2021/cashbook-18, pull requests merged in 2021-08, with the labels that each got.

#50 [feature] history API 작성
  server/api/routes/history.ts
  server/controllers/history.controller.ts
  server/repositories/history.repository.ts
  server/services/history.services.ts
  server/types/types.ts
Labels: BE, enhancement

#52 [feature] Oauth 관련 로그인 처리 및 미들웨어 적용
  server/api/middlewares/auth.middleware.ts
  server/api/routes/category.ts
  server/api/routes/payment.ts
  server/api/routes/user.ts
  server/config/index.ts
  server/controllers/category.controller.ts
  server/controllers/payment.controller.ts
  server/controllers/user.controller.ts
  server/entities/RefreshToken.ts
  server/entities/User.ts
  server/package-lock.json
  server/package.json
  server/repositories/refreshToken.repository.ts
  server/repositories/user.repository.ts
  server/services/token.services.ts
  server/services/user.services.ts
  server/tsconfig.json
  server/types/express.d.ts
  server/types/types.ts
  server/utils/getPayload.ts
  server/utils/jwtAuth.ts
Labels: BE, enhancement

#54 [feature] 백엔드 API 프론트단에 연결
  client/package-lock.json
  client/package.json
  client/src/api/auth.ts
  client/src/api/category.ts
  client/src/api/payment.ts
  client/webpack.config.js
  server/api/middlewares/auth.middleware.ts
  server/controllers/category.controller.ts
  server/loaders/express.loader.ts
  server/package-lock.json
  server/package.json
Labels: BE, FE, enhancement

#56 [refactor] typedi를 이용한 서비스-컨트롤로 간 의존성 주입 작성
  server/controllers/category.controller.ts
  server/controllers/history.controller.ts
  server/controllers/payment.controller.ts
  server/controllers/user.controller.ts
  server/services/category.services.ts
  server/services/history.services.ts
  server/services/payment.services.ts
  server/services/token.services.ts
  server/services/user.services.ts
Labels: BE, refactor

#58 [refactor] options 및 반복 기능 헬퍼 함수화
  server/config/index.ts
  server/controllers/category.controller.ts
  server/controllers/payment.controller.ts
  server/controllers/user.controller.ts
  server/loaders/express.loader.ts
  server/services/history.services.ts
  server/services/user.services.ts
  server/utils/getPayload.ts
  server/utils/helper.ts
Labels: BE, refactor

#63 [feature] 유저 페이지 생성
  client/src/Components/CategoryIcon/index.ts
  client/src/Components/CategoryIcon/styles.scss
  client/src/Components/Header/index.ts
  client/src/Components/Header/styles.scss
  client/src/Components/User/index.ts
  client/src/Components/User/styles.scss
  client/src/Model/PaymentsModel.ts
  client/src/View/UserView/index.ts
  client/src/View/UserView/styles.scss
  client/src/api/auth.ts
  client/src/api/payment.ts
  client/src/api/user.ts
  client/src/assets/svgIcons.ts
  client/src/main.ts
  client/src/scss/index.scss
  client/src/utils/types.ts
  server/api/routes/user.ts
  server/controllers/payment.controller.ts
  server/controllers/user.controller.ts
  server/loaders/express.loader.ts
  server/package-lock.json
  server/package.json
  server/repositories/user.repository.ts
  server/services/user.services.ts
  server/utils/helper.ts
Labels: BE, FE

#64 [feature] 컴포넌트 구조 재조정 및 달력 기능 일부 작성
  client/src/Components/Calendar/index.ts
  client/src/Components/Calendar/styles.scss
  client/src/Components/CategoryTag/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryList/index.ts
  client/src/Components/HistoryList/styles.scss
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Components/List/index.ts
  client/src/Components/Main/index.ts
  client/src/Components/PriceBar/index.ts
  client/src/Components/PriceBar/styles.scss
  client/src/Controller/CalendarController.ts
  client/src/Controller/HeaderController.ts
  client/src/Controller/TodoController.ts
  client/src/Model/MainModel.ts
  client/src/View/CalendarView/index.ts
  client/src/View/CalendarView/styles.scss
  client/src/View/MainView/index.ts
  client/src/utils/helper.ts
  client/src/utils/types.ts
Labels: FE, enhancement, refactor

#65 [feature] Calendar 컴포넌트 내역 조회 서버 API 연동 및 기능 작성
  client/package-lock.json
  client/package.json
  client/src/Components/Calendar/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/InputBar/index.ts
  client/src/Components/Main/index.ts
  client/src/Components/PriceBar/index.ts
  client/src/Components/User/index.ts
  client/src/Controller/CalendarController.ts
  client/src/Controller/HeaderController.ts
  client/src/Model/HistoryModel.ts
  client/src/api/history.ts
  client/src/assets/dummy.ts
  client/src/utils/types.ts
  server/api/routes/history.ts
  server/controllers/history.controller.ts
Labels: BE, FE, enhancement

#66 [feat] 카테고리 API 연동
  client/src/Components/CategoryIcon/index.ts
  client/src/Components/CategoryIcon/styles.scss
  client/src/Components/User/index.ts
  client/src/Components/User/styles.scss
  client/src/Components/UserCategory/index.ts
  client/src/Components/UserCategory/styles.scss
  client/src/Model/CategoryModel.ts
  client/src/View/UserView/index.ts
  client/src/api/category.ts
  client/src/assets/svgIcons.ts
  client/src/utils/types.ts
  server/repositories/category.repository.ts
Labels: FE, enhancement

#67 [feature] 지불 수단 API 연동
  client/src/Components/PaymentElem/index.ts
  client/src/Components/PaymentElem/styles.scss
  client/src/Components/User/index.ts
  client/src/Components/UserPayment/index.ts
  client/src/Components/UserPayment/styles.scss
  client/src/Model/PaymentsModel.ts
  client/src/api/payment.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#70 [feature] 카테고리/결제수단 중복으로 생성되는 문제 수정
  server/repositories/category.repository.ts
  server/repositories/payment.repository.ts
  server/services/category.services.ts
  server/services/payment.services.ts
  server/services/user.services.ts
Labels: BE, enhancement

#69 [feature] 도넛 차트 기본 도형 및 애니메이션과 지출/수입 퍼센트 내역 작성
  client/src/Components/Chart/index.ts
  client/src/Components/Chart/styles.scss
  client/src/Components/DonutChart/index.ts
  client/src/Components/DonutChart/styles.scss
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryCategoryCard/styles.scss
  client/src/Components/HistoryDayCard/index.ts
  client/src/View/ChartsView/index.ts
  client/src/View/ChartsView/styles.scss
Labels: FE, enhancement

#72 [feature] 도넛 차트 API 연동 및 애니메이션 작성 + 라인 차트 기본 구독 모델 설정
  client/src/Components/DonutChart/index.ts
  client/src/Components/DonutChart/styles.scss
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryCategoryCard/styles.scss
  client/src/Components/LineChart/index.ts
  client/src/Components/LineChart/styles.scss
  client/src/Controller/ChartController.ts
  client/src/Core/Component.ts
  client/src/Model/HistoryModel.ts
  client/src/View/ChartsView/index.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#73 [feature] 메인 페이지 API 연동
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Components/Main/styles.scss
  client/src/Model/HistoryModel.ts
  client/src/View/MainView/styles.scss
  client/src/api/history.ts
  client/src/assets/svgIcons.ts
  client/src/utils/types.ts
  server/controllers/history.controller.ts
Labels: FE, enhancement

#76 [feature] History 날짜 제대로 삽입되지 않던 문제 수정
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Core/Component.ts
  server/repositories/history.repository.ts
  server/types/types.ts
Labels: BE, FE, bug

#77 [feature] category dropdown 컴포넌트 작성 및 입력창과 연동
  client/src/Components/CategoryDropdown/index.ts
  client/src/Components/CategoryDropdown/styles.scss
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  server/services/category.services.ts
Labels: FE, enhancement

#78 [feature] 차트에 카테고리 색상 추가
  client/src/Components/CategoryTag/index.ts
  client/src/Components/DonutChart/index.ts
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryList/index.ts
  client/src/Components/LineChart/index.ts
  client/src/Components/Main/index.ts
  client/src/Controller/ChartController.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#81 [feature] 결제수단 드랍다운 컴포넌트 작성
  client/src/Components/CategoryDropdown/index.ts
  client/src/Components/CategoryDropdown/styles.scss
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Components/PaymentDropdown/index.ts
  client/src/Components/PaymentDropdown/styles.scss
Labels: FE, enhancement

#82 [feature] Histroy Update/Delete API 연동
  client/src/Components/CategoryDropdown/index.ts
  client/src/Components/DropDown/index.ts
  client/src/Components/DropDown/styles.scss
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryList/index.ts
  client/src/Components/InputBar/index.ts
  client/src/Components/Main/index.ts
  client/src/Components/PaymentDropdown/index.ts
  client/src/Model/HistoryModel.ts
  client/src/api/history.ts
  client/src/utils/helper.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#84 [feature] history stat API 추가
  client/src/api/history.ts
  server/api/routes/history.ts
  server/controllers/history.controller.ts
  server/repositories/history.repository.ts
  server/services/history.services.ts
Labels: BE, FE

#85 [feature] 메인페이지 인풋창 디자인 초안 및 CRUD 관련 버그 수정
  client/src/Components/CategoryDropdown/index.ts
  client/src/Components/CategoryDropdown/styles.scss
  client/src/Components/CategoryTag/styles.scss
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryList/styles.scss
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Components/Main/index.ts
  client/src/Components/PaymentDropdown/index.ts
  client/src/Components/PaymentDropdown/styles.scss
  client/src/Core/Component.ts
  client/src/scss/index.scss
  client/src/scss/reset.scss
  client/src/scss/theme.scss
  client/src/utils/helper.ts
Labels: FE, enhancement

#87 [bugfix] 도넛 차트 퍼센트 계산 문제 수정
  client/src/Components/DonutChart/index.ts
  client/src/Components/DropDown/index.ts
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryCategoryCard/styles.scss
  client/src/Controller/ChartController.ts
  client/src/scss/animation.scss
Labels: FE, bug, enhancement

#89 [bugfix] 드랍다운 관련 버그 및 이슈 해결 + 기능 추가
  client/src/Components/DropDown/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryCategoryCard/styles.scss
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryList/index.ts
  client/src/Components/HistoryList/styles.scss
  client/src/Components/InputBar/index.ts
  client/src/Components/InputBar/styles.scss
  client/src/Components/Main/index.ts
  client/src/Components/PaymentDropdown/styles.scss
  client/src/scss/animation.scss
Labels: FE, bug, enhancement

#93 [feature] line chart 마크업 및 API 연동
  client/src/Components/LineChart/index.ts
  client/src/Components/LineChart/styles.scss
  client/src/Model/HistoryModel.ts
  client/src/View/ChartsView/index.ts
  client/src/View/ChartsView/styles.scss
  client/src/api/history.ts
  client/src/utils/types.ts
  server/api/routes/history.ts
  server/controllers/history.controller.ts
  server/repositories/history.repository.ts
  server/services/history.services.ts
Labels: BE, FE

#94 [feature] 개발/프로덕션 배포 환경 분리 진행
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/api/auth.ts
  client/src/api/category.ts
  client/src/api/history.ts
  client/src/api/payment.ts
  client/src/api/user.ts
  client/webpack.config.js
  server/config/index.ts
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: BE, FE, core, enhancement

#98 [feature] no data 관련 컴포넌트 작성 및 연동
  client/src/Components/HistoryCategoryCard/index.ts
  client/src/Components/HistoryCategoryCard/styles.scss
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/NoFound/index.ts
  client/src/Components/NoFound/styles.scss
  client/src/View/UserView/index.ts
  client/src/assets/box.svg
  client/src/assets/index.ts
  client/src/scss/animation.scss
Labels: enhancement, FE

#99 [feature] 수입 카테고리도 라인 차트로 출력
  client/src/Components/LineChart/index.ts
  client/src/Components/LineChart/styles.scss
  client/src/Model/HistoryModel.ts
  client/src/api/history.ts
  client/src/utils/types.ts
  server/api/routes/history.ts
  server/controllers/history.controller.ts
  server/repositories/history.repository.ts
  server/services/history.services.ts
  server/types/types.ts
Labels: FE

#100 [feature] 로딩 컴포넌트 추가
  client/src/Components/Loading/index.ts
  client/src/Components/Loading/styles.scss
  client/src/View/UserView/index.ts
Labels: enhancement, FE

#101 [refactor] 기타 페이지 애니메이션 적용
  client/src/Components/HistoryList/styles.scss
  client/src/View/CalendarView/styles.scss
  client/src/View/ChartsView/styles.scss
  client/src/View/UserView/index.ts
  client/src/View/UserView/styles.scss
  client/src/assets/docgo.jpg
  client/src/assets/index.ts
  client/src/scss/animation.scss
Labels: FE, refactor

#102 [feature] 반응형 디자인 설계
  client/src/Components/Header/styles.scss
  client/src/scss/index.scss
Labels: enhancement, FE

#103 [feature] 메인, 캘린더 페이지 반응형 구현
  client/src/Components/Calendar/styles.scss
  client/src/Components/CategoryTag/styles.scss
  client/src/Components/HistoryList/styles.scss
  client/src/Components/InputBar/styles.scss
  client/src/Components/Main/styles.scss
  client/src/Components/PriceBar/styles.scss
  client/src/Controller/CalendarController.ts
  client/src/View/CalendarView/styles.scss
Labels: enhancement, FE

#105 [bugfix] 유저 카테고리 생성시 랜덤 색상 오류 해결
  client/src/Components/UserCategory/index.ts
Labels: FE

#106 [feature] 유저페이지 반응형 디자인 설계
  client/src/Components/DonutChart/styles.scss
  client/src/Components/Header/styles.scss
  client/src/Components/PaymentElem/styles.scss
  client/src/Components/User/styles.scss
  client/src/Components/UserCategory/styles.scss
  client/src/Components/UserPayment/styles.scss
  client/src/Controller/ChartController.ts
  client/src/View/ChartsView/styles.scss
  client/src/View/UserView/styles.scss
  client/src/scss/animation.scss
Labels: enhancement, FE

#107 refactor: 기타 버그 및 오류, 세부 디자인 수정
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/HistoryDayCard/styles.scss
  client/src/Components/HistoryList/styles.scss
  client/src/Components/InputBar/styles.scss
  client/src/Components/LineChart/index.ts
  client/src/Components/Main/index.ts
  client/src/Components/Main/styles.scss
  client/src/Components/User/styles.scss
  client/src/Components/UserPayment/index.ts
  client/src/Core/Component.ts
  client/src/Model/HistoryModel.ts
  client/src/main.ts
  client/src/scss/animation.scss
  client/src/utils/types.ts
  client/webpack.config.js
Labels: bug, enhancement, FE

#108 hotfix: 0을 나누는 오류 해결
  client/src/Components/LineChart/index.ts
Labels: FE

#109 Hotfix/usr payment
  server/services/payment.services.ts
Labels: bug
