Repository woowa-techcamp-2021/cashbook-18, pull requests merged in 2021-07, with the labels that each got.

#10 [chore] 초기 프론트엔드 설정 및 옵저버 패턴 구조 적용
  .eslintrc
  .prettierrc
  client/.babelrc
  client/images.d.ts
  client/package-lock.json
  client/package.json
  client/src/Components/TestComponent/index.ts
  client/src/Components/TestComponent/styles.scss
  client/src/Controller/TodoController.ts
  client/src/Core/Component.ts
  client/src/Core/Observable.ts
  client/src/Core/Router.ts
  client/src/Core/Store.ts
  client/src/Model/TodoModel.ts
  client/src/View/Detail/index.ts
  client/src/View/Detail/styles.scss
  client/src/View/Home/index.ts
  client/src/View/Home/styles.scss
  client/src/assets/Logoo.png
  client/src/assets/add-mint.svg
  client/src/assets/heart-fill.svg
  client/src/assets/index.ts
  client/src/assets/myom_logo7.png
  client/src/assets/tea.svg
  client/src/index.html
  client/src/main.ts
  client/src/reset.scss
  client/src/utils/helper.ts
  client/src/utils/types.ts
  client/tsconfig.json
  client/webpack.config.js
  server/package.json
Labels: core

#12 [feature] 문서 기본 구조 설계 및 헤더 구조 작성
  client/src/Components/Header/index.ts
  client/src/Components/Header/styles.scss
  client/src/Components/TestComponent/index.ts
  client/src/Components/TestComponent/styles.scss
  client/src/Core/Router.ts
  client/src/View/Calendar/index.ts
  client/src/View/Charts/index.ts
  client/src/View/Detail/index.ts
  client/src/View/Detail/styles.scss
  client/src/View/Home/index.ts
  client/src/View/Main/index.ts
  client/src/index.html
  client/src/main.ts
Labels: FE, enhancement

#13 [refactor] scss 폴더 구조 재정립
  client/src/Components/Header/index.ts
  client/src/View/Home/index.ts
  client/src/View/Main/index.ts
  client/src/View/Main/styles.scss
  client/src/assets/Logoo.png
  client/src/assets/add-mint.svg
  client/src/assets/heart-fill.svg
  client/src/assets/index.ts
  client/src/assets/myom_logo7.png
  client/src/assets/svgIcons.ts
  client/src/assets/tea.svg
  client/src/main.ts
  client/src/scss/index.scss
  client/src/scss/reset.scss
  client/src/scss/theme.scss
Labels: FE, refactor

#14 Feature/header
  client/src/Components/Header/index.ts
  client/src/Components/Header/styles.scss
  client/src/assets/svgIcons.ts
Labels: FE, enhancement

#16 [refactor] Component 클래스 unmount 이벤트 메서드 추가
  client/src/Components/Header/index.ts
  client/src/Core/Component.ts
  client/src/Core/Router.ts
  client/src/Model/TodoModel.ts
  client/src/View/Calendar/index.ts
  client/src/View/Charts/index.ts
  client/src/View/Home/index.ts
  client/src/View/Main/index.ts
  client/src/View/Main/styles.scss
  client/src/main.ts
  client/src/utils/types.ts
Labels: FE, refactor

#17 [feature] CalendarView 와 Calendar 컴포넌트 기본 마크업 구조 작성
  client/src/Components/Calendar/index.ts
  client/src/Components/Calendar/styles.scss
  client/src/Components/Header/index.ts
  client/src/View/Calendar/index.ts
  client/src/View/CalendarView/index.ts
  client/src/View/CalendarView/styles.scss
  client/src/main.ts
  client/src/scss/index.scss
  client/src/scss/theme.scss
Labels: FE, enhancement

#19 [chore] 프론트엔드에서 테스트 할 더미데이터 작성
  client/src/assets/dummy.ts
Labels: FE, core

#20 [feature] main 페이지 간단한 마크업
  client/src/Components/Main/index.ts
  client/src/Components/Main/styles.scss
  client/src/View/Main/styles.scss
  client/src/View/MainView/index.ts
  client/src/View/MainView/styles.scss
  client/src/assets/svgIcons.ts
  client/src/main.ts
  client/src/scss/index.scss
  client/src/scss/theme.scss
Labels: FE, enhancement

#21 [feature] 달력 컴포넌트 동적 생성하도록 작성
  client/src/Components/Calendar/index.ts
  client/src/Components/Header/index.ts
  client/src/Core/Observable.ts
  client/src/Core/Store.ts
  client/src/Model/DateModel.ts
  client/src/Model/TodoModel.ts
  client/src/View/CalendarView/index.ts
  client/src/View/Home/index.ts
  client/src/View/Home/styles.scss
  client/src/main.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#23 [feature] Chart 뷰 및 컴포넌트 기본 포맷 마크업 간단 작성
  client/src/Components/Chart/index.ts
  client/src/Components/Chart/styles.scss
  client/src/View/Charts/index.ts
  client/src/View/ChartsView/index.ts
  client/src/View/ChartsView/styles.scss
  client/src/View/Main/index.ts
  client/src/main.ts
  client/src/scss/theme.scss
Labels: FE, enhancement

#25 [feature] 메인 페이지 기능 추가
  client/src/Components/CategoryTag/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/HistoryDayCard/index.ts
  client/src/Components/List/index.ts
  client/src/Components/List/styles.scss
  client/src/Components/Main/index.ts
  client/src/Components/Main/styles.scss
  client/src/Core/Component.ts
  client/src/Model/MainModel.ts
  client/src/View/MainView/index.ts
  client/src/View/MainView/styles.scss
  client/src/assets/svgIcons.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#26 [chore] server 관련 기본 폴더 및 파일 구조 보일러 플레이트 작성
  server/api/index.ts
  server/api/middlewares/auth.middleware.ts
  server/api/routes/user.routes.ts
  server/app.ts
  server/config/index.ts
  server/controllers/user.controller.ts
  server/database/init.sql
  server/entities/Category.ts
  server/entities/History.ts
  server/entities/Payment.ts
  server/entities/User.ts
  server/entities/UserCategory.ts
  server/entities/UserPayment.ts
  server/loaders/express.loader.ts
  server/loaders/index.ts
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/repositories/user.ropository.ts
  server/services/user.services.ts
  server/tsconfig.json
Labels: BE, core

#28 [#27] chore: 서버 자동 배포 스크립트 추가
  script/deploy.sh
Labels: core

#29 [feature] main 유효성 검사 기능 추가
  client/src/View/MainView/index.ts
  client/src/View/MainView/styles.scss
  client/src/utils/types.ts
Labels: FE, enhancement

#32 [chore] typeorm 을 이용한 EC2 데이터베이스 연결
  server/api/index.ts
  server/api/routes/user.ts
  server/app.ts
  server/config/index.ts
  server/database/init.sql
  server/entities/History.ts
  server/entities/User.ts
  server/loaders/database.loader.ts
  server/loaders/index.ts
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
Labels: BE, core

#38 [feature] API 기본 포맷 작성 및 테스트
  server/api/index.ts
  server/api/routes/category.ts
  server/api/routes/history.ts
  server/api/routes/payment.ts
  server/api/routes/user.ts
  server/config/index.ts
  server/controllers/category.controller.ts
  server/controllers/history.controller.ts
  server/entities/History.ts
  server/loaders/express.loader.ts
  server/ormconfig.ts
  server/repositories/category.repository.ts
  server/repositories/history.repository.ts
  server/repositories/user.repository.ts
  server/services/category.services.ts
  server/services/history.services.ts
  server/services/user.services.ts
  server/types/types.ts
Labels: BE, enhancement

#41 [feature] main 컴포넌트 약간의 버그 수정
  client/src/Components/CategoryTag/index.ts
  client/src/Model/MainModel.ts
  client/src/View/MainView/index.ts
Labels: FE, enhancement

#42 [feature] header 아이콘 페이지에 맞게 활성화
  client/src/Components/Header/index.ts
  client/src/Components/Header/styles.scss
Labels: FE, enhancement

#43 [feature] Calendar 더미데이터 연동 작업 모델 구독 구현
  client/src/Components/Calendar/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/Main/index.ts
  client/src/assets/dummy.ts
  client/src/utils/types.ts
Labels: FE, enhancement

#39 [feature] 카테고리 API 기본 코드 베이스 및 기본 로직 구현
  server/api/routes/category.ts
  server/controllers/category.controller.ts
  server/entities/UserCategory.ts
  server/repositories/category.repository.ts
  server/services/category.services.ts
  server/tsconfig.json
  server/types/express.d.ts
  server/types/types.ts
Labels: BE, enhancement

#40 [feature] 결제수단 API 기본 코드 베이스 및 기본 로직 구현
  server/api/routes/payment.ts
  server/controllers/payment.controller.ts
  server/repositories/payment.repository.ts
  server/services/payment.services.ts
  server/types/types.ts
Labels: BE, enhancement

#46 [refactor] observer 패턴 구조에서 발생하는 리-렌더링 중복 문제 해결
  client/src/Components/Calendar/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/Main/index.ts
  client/src/Core/Component.ts
  client/src/Core/Observable.ts
  client/src/Model/DateModel.ts
  client/src/Model/MainModel.ts
  client/src/View/MainView/index.ts
  client/src/utils/helper.ts
  client/src/utils/types.ts
Labels: FE, refactor

#49 [feature] diffing 알고리즘을 적용한 부분 렌더링 구현
  client/src/Components/Calendar/index.ts
  client/src/Components/Header/index.ts
  client/src/Components/Main/index.ts
  client/src/Components/Main/styles.scss
  client/src/Core/Component.ts
  client/src/Core/Router.ts
  client/src/Core/diffing.ts
  client/src/Model/MainModel.ts
  client/src/main.ts
  client/src/utils/helper.ts
  client/src/utils/types.ts
Labels: FE, enhancement
